# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90dd11855e0a2805bab84ef208d22cd8"
name = "QRCODE"
handle = "qrcode-293"
application_url = "https://nightlife-temporarily-berkeley-shareware.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nightlife-temporarily-berkeley-shareware.trycloudflare.com/auth/callback",
  "https://nightlife-temporarily-berkeley-shareware.trycloudflare.com/auth/shopify/callback",
  "https://nightlife-temporarily-berkeley-shareware.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
